version: '3'

networks:
  default: {}
  core_proxy:
    external: true

services:
  app:
    image: niruix/sshwifty
    container_name: ssh
    restart: always
    environment:
      - SSHWIFTY_SHAREDKEY=${password}
    networks:
      - default
      - core_proxy
    labels:
      - traefik.enable=true
      - traefik.port=8182
      - traefik.frontend.rule=Host:${url}
      - traefik.frontend.redirect.entryPoint=https
      - traefik.docker.network=core_proxy
      - ghosts.host=${url}
      - ghosts.proto=https
      - ghosts.logo=static/logos/terminal.png
      - ghosts.category=tools
