version: '3'

services:
  app:
    image: clue/h5ai
    container_name: browser
    volumes:
      - media:/var/www
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:${traefik_url}
      - traefik.frontend.entryPoints=${traefik_protocol:-http}
      - traefik.home=true

volumes:
  media:
    external: true
