version: '3'

services:
  app:
    image: clue/h5ai
    container_name: browser
    volumes:
      - media:/var/www
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:${traefik_url}
      - traefik.frontend.auth.basic=${traefik_auth}
      - traefik.home=true
      - traefik.home.image=logos/h5ai.png
      - traefik.home.category=Tools

volumes:
  media:
    external: true
