version: '3'

volumes:
  openvpn: {}

networks:
  default: {}
  core_proxy:
    external: true

services:
  server:
    image: jpetazzo/dockvpn
    container_name: vpn
    restart: always
    privileged: true
    volumes:
      - openvpn:/etc/openvpn
      - ./run:/usr/local/sbin/run
      - ./serveconfig:/usr/local/sbin/serveconfig
    ports:
      - 1194:1194/udp
      - 8080:443/tcp
    networks:
      - default

  config:
    image: jpetazzo/dockvpn
    container_name: vpn-config
    restart: always
    command: serveconfig
    volumes:
      - openvpn:/etc/openvpn
      - ./run:/usr/local/sbin/run
      - ./serveconfig:/usr/local/sbin/serveconfig
    networks:
      - default
      - core_proxy
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.protocol=https
      - traefik.frontend.rule=Host:${url}
      - traefik.frontend.auth.basic=${auth}
      - ghosts.host=${url}
      - ghosts.proto=https
      - ghosts.auth=true
      - ghosts.name=vpn
      - ghosts.logo=static/logos/vpn.png
      - ghosts.category=tools

