version: '3'

services:
  server:
    image: jpetazzo/dockvpn
    container_name: vpn
    privileged: true
    volumes:
      - ./run:/usr/local/sbin/run
      - ./serveconfig:/usr/local/sbin/serveconfig
    ports:
      - 1194:1194/udp
      - 8080:443/tcp

  config:
    image: jpetazzo/dockvpn
    container_name: vpn-config
    command: serveconfig
    volumes_from:
      - server
    volumes:
      - ./run:/usr/local/sbin/run
      - ./serveconfig:/usr/local/sbin/serveconfig
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.protocol=https
      - traefik.frontend.rule=Host:${traefik_url}
      - traefik.frontend.entryPoints=${traefik_protocol:-http}
      - traefik.home=true
