version: '3'

services:
  app:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    ports:
      - 8989:8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - media:/downloads
      - media:/tv
      - config:/config
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - traefik.enable=true
      - traefik.port=8989
      - traefik.frontend.rule=Host:${traefik_url}
      - traefik.frontend.auth.basic=${traefik_auth}
      - traefik.home=true
      - traefik.home.image=logos/sonarr.png
      - traefik.home.category=Downloads

volumes:
  media:
    external: true
  config:
    driver: "local"
