version: '3'

services:
  app:
    image: linuxserver/pydio
    container_name: pydio
    links:
      - db
    volumes:
      - media:/data/files
      - /etc/localtime:/etc/localtime:ro
      - config:/config
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - traefik.enable=true
      - traefik.port=443
      - traefik.protocol=https
      - traefik.frontend.rule=Host:${traefik_url}
      - traefik.frontend.entryPoints=${traefik_protocol:-http}
      - traefik.home=true

  db:
    image: mysql
    container_name: pydio-db
    environment:
      - MYSQL_ROOT_PASSWORD=${db_password}
      - MYSQL_DATABASE=${db_database}

volumes:
  media:
    external: true
  config:
    driver: "local"
