version: '3'

services:
  app:
    image: linuxserver/htpcmanager
    container_name: htpcmanager
    ports:
      - 8085:8085
    volumes:
      - config:/config
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - traefik.enable=true
      - traefik.port=8085
      - traefik.frontend.rule=Host:${traefik_url}
      - traefik.home=true
      - traefik.home.alias=HtpcManager
      - traefik.home.category=Tools

volumes:
  config:
    driver: "local"
