version: '3'

services:
  app:
    image: jlesage/jdownloader-2
    container_name: jdownloader
    restart: always
    ports:
      - 5800:5800
    volumes:
      - media:/output
      - config:/config
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    labels:
      - traefik.enable=true
      - traefik.port=5800
      - traefik.frontend.rule=Host:${traefik_url}
      - traefik.frontend.auth.basic=${traefik_auth}
      - traefik.home=true
      - traefik.home.category=Downloads

volumes:
  media:
    external: true
  config:
    driver: "local"
