version: '3'

volumes:
  config: {}
  media:
    external: true

networks:
  default: {}
  core_proxy:
    external: true

services:
  app:
    image: jlesage/jdownloader-2
    container_name: jdownloader
    restart: always
    volumes:
      - media:/output
      - config:/config
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    networks:
      - default
      - core_proxy
    labels:
      - traefik.enable=true
      - traefik.port=5800
      - traefik.frontend.rule=Host:${url}
      - traefik.frontend.auth.basic=${auth}
      - traefik.frontend.redirect.entryPoint=https
      - traefik.docker.network=core_proxy
      - ghosts.host=${url}
      - ghosts.proto=https
      - ghosts.auth=true
      - ghosts.category=downloads

