version: '3'

services:
  app:
    image: jlesage/jdownloader-2
    container_name: jdownloader
    restart: always
    volumes:
      - media:/output
      - config:/config
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    labels:
      - traefik.enable=true
      - traefik.port=5800
      - traefik.frontend.rule=Host:${url}
      - traefik.frontend.auth.basic=${auth}
      - ghosts.host=${url}
      - ghosts.proto=https
      - ghosts.auth=true
      - ghosts.category=downloads

volumes:
  media:
    external: true
  config:
    driver: "local"
