version: '3'

services:
  proxy:
    image: portainer/portainer
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.port=9000
      - traefik.frontend.rule=Host:${traefik_url}
      - traefik.home=true
      - traefik.home.image=logos/portainer.png
      - traefik.home.category=Core
