version: '3'

volumes:
  config: {}

networks:
  default: {}
  core_proxy:
    external: true

services:
  app:
    image: linuxserver/ombi
    container_name: ombi
    restart: always
    ports:
      - 3579:3579
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - config:/config
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - default
      - core_proxy
    labels:
      - traefik.enable=true
      - traefik.port=3579
      - traefik.frontend.rule=Host:${url}
      - traefik.frontend.redirect.entryPoint=https
      - traefik.docker.network=core_proxy
      - ghosts.host=${url}
      - ghosts.proto=https
      - ghosts.logo=static/logos/ombi.png
      - ghosts.category=media

