version: '3'

services:
  app:
    image: linuxserver/ombi
    container_name: ombi
    ports:
      - 3579:3579
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - config:/config
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - traefik.enable=true
      - traefik.port=3579
      - traefik.frontend.rule=Host:${traefik_url}
      - traefik.home=true
      - traefik.home.alias=Requests
      - traefik.home.image=logos/ombi.png
      - traefik.home.category=Media

volumes:
  config:
    driver: "local"
