version: '3'

services:
  app:
    image: linuxserver/projectsend
    container_name: projectsend
    volumes:
      - media:/data
      - config:/config
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:${traefik_url}
      - traefik.home=true
      - traefik.home.alias=ProjectSend
      - traefik.home.category=Tools

volumes:
  media:
    external: true
  config:
    driver: "local"
