version: '2'

services:
  app:
    image: "kevan/dockerui"
    container_name: "docker-ui"
    privileged: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file: "app.env"
