version: '3'

networks:
  default: {}
  core_proxy:
    external: true

services:
  app:
    image: starbix/synclounge
    container_name: synclounge
    restart: always
    environment:
      - DOMAIN=${client_url}
    networks:
      - default
      - core_proxy
    labels:
      - traefik.enable=true
      - traefik.frontend.entryPoints=http,ws,wss
      - traefik.frontend.redirect.entryPoint=false
      - traefik.client.port=8088
      - traefik.server.port=8089
      - traefik.client.frontend.rule=Host:${client_url}
      - traefik.server.frontend.rule=Host:${server_url}
      - traefik.docker.network=core_proxy
      - ghosts.host=${client_url}
      - ghosts.proto=http
      - ghosts.logo=static/logos/synclounge.png
      - ghosts.category=media

