version: '3'

networks:
  default: {}
  core_proxy:
    external: true

services:
  app:
    image: starbix/synclounge
    container_name: synclounge
    restart: always
    ports:
      - 8089:8089
    environment:
      - DOMAIN=${url}
    networks:
      - default
      - core_proxy
    labels:
      - traefik.enable=true
      - traefik.port=8088
      - traefik.frontend.rule=Host:${url}
      - traefik.docker.network=core_proxy
      - ghosts.host=${url}
      - ghosts.proto=https
      - ghosts.logo=static/logos/synclounge.png
      - ghosts.category=media

