version: '3'

networks:
  default: {}
  core_proxy:
    external: true

services:
  app:
    image: starbix/synclounge
    container_name: synclounge
    restart: always
    environment:
      - DOMAIN=${url}
      - autoJoin=true
      - autoJoinServer=http://${url}/slserver
    networks:
      - default
      - core_proxy
    labels:
      - traefik.enable=true
      - traefik.frontend.entryPoints=http,ws,wss
      - traefik.client.port=8088
      - traefik.server.port=8089
      - traefik.client.frontend.rule=Host:${url}
      - traefik.server.frontend.rule=Host:${url};PathPrefix:/slserver
      - traefik.docker.network=core_proxy
      - ghosts.host=${url}
      - ghosts.proto=http
      - ghosts.logo=static/logos/synclounge.png
      - ghosts.category=media

