version: '3'

volumes:
  config: {}
  media:
    external: true

networks:
  default: {}
  core_proxy:
    external: true

services:
  app:
    image: linuxserver/plex
    container_name: plex
    restart: always
    ports:
      - 32400:32400
    volumes:
      - media:/data
      - config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=latest
    networks:
      - default
      - core_proxy
    labels:
      - traefik.enable=true
      - traefik.port=32400
      - traefik.frontend.rule=Host:${url}
      - traefik.frontend.redirect.entryPoint=https
      - traefik.docker.network=core_proxy
      - ghosts.host=${url}
      - ghosts.proto=https
      - ghosts.logo=static/logos/plex.png
      - ghosts.category=media

