version: '3'

services:
  app:
    image: linuxserver/plex
    container_name: plex
    restart: always
    ports:
      - 32400:32400
    volumes:
      - media:/data
      - config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=latest
    labels:
      - traefik.enable=true
      - traefik.port=32400
      - traefik.frontend.rule=Host:${url}
      - ghosts.host=${url}
      - ghosts.proto=https
      - ghosts.logo=static/logos/plex.png
      - ghosts.category=media

volumes:
  media:
    external: true
  config:
    driver: "local"
