version: '3'

services:
  app:
    image: linuxserver/plex
    container_name: plex
    ports:
      - 32400:32400
    volumes:
      - media:/data
      - config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=latest
    labels:
      - traefik.enable=true
      - traefik.port=32400
      - traefik.frontend.rule=Host:${traefik_url}
      - traefik.frontend.auth.basic=${traefik_auth}
      - traefik.home=true
      - traefik.home.image=logos/plex.png
      - traefik.home.category=Media

volumes:
  media:
    external: true
  config:
    driver: "local"
