version: '3'

volumes:
  config: {}

networks:
  default: {}
  core_proxy:
    external: true

services:
  app:
    image: linuxserver/muximux
    container_name: muximux
    restart: always
    volumes:
      - config:/config
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - default
      - core_proxy
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:${url}
      - traefik.frontend.redirect.entryPoint=https
      - traefik.docker.network=core_proxy
      - ghosts.host=${url}
      - ghosts.proto=https
      - ghosts.category=tools

