version: '3'

services:
  app:
    image: linuxserver/muximux
    container_name: muximux
    volumes:
      - config:/config
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:${traefik_url}
      - traefik.frontend.auth.basic=${traefik_auth}
      - traefik.home=true
      - traefik.home.category=Tools

volumes:
  config:
    driver: "local"
