version: '3'

services:
  app:
    image: linuxserver/muximux
    container_name: muximux
    restart: always
    volumes:
      - config:/config
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:${url}
      - ghosts.host=${url}
      - ghosts.proto=https
      - ghosts.category=tools

volumes:
  config:
    driver: "local"
