version: '3'

volumes:
  media:
    external: true

networks:
  default: {}
  core_proxy:
    external: true

services:
  app:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: always
    user: 1000:1000
    volumes:
      - $HOME:/srv/local
      - media:/srv/media
      - ./database.db:/etc/database.db
      - ./filebrowser.json:/.filebrowser.json
    networks:
      - default
      - core_proxy
    labels:
      - traefik.enable=true
      - traefik.port=8888
      - traefik.frontend.rule=Host:${url}
      - traefik.frontend.redirect.entryPoint=https
      - traefik.docker.network=core_proxy
      - ghosts.host=${url}
      - ghosts.proto=https
      - ghosts.category=tools

