version: '3'

networks:
  default: {}
  core_proxy:
    external: true

services:
  app:
    image: lobre/rmuploader
    container_name: rmuploader
    restart: always
    environment:
      - RMUPLOADER_CODE=${code}
    networks:
      - default
      - core_proxy
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:${url}
      - traefik.frontend.auth.basic=${auth}
      - traefik.frontend.redirect.entryPoint=https
      - traefik.docker.network=core_proxy
      - ghosts.host=${url}
      - ghosts.proto=https
      - ghosts.auth=true
      - ghosts.category=tools

