version: '3'

volumes:
  media:
    external: true

networks:
  default: {}

services:
  app:
    image: mcreations/ftp
    container_name: ftp
    restart: always
    volumes:
      - $HOME:/data/admin/local
      - media:/data/admin/media
    ports:
      - "21:21"
      - "65000-65004:65000-65004"
    networks:
      - default
    environment:
      - PASV_MIN_PORT=65000
      - PASV_MAX_PORT=65004
      - FTP_USER=${ftp_user}
      - FTP_PASS=${ftp_password}
      - HOST=${ftp_host}

