defaultEntryPoints = ["http", "https", "ws", "wss"]
InsecureSkipVerify = true

[web]
address = ":8080"

[entryPoints]

[entryPoints.http]
address = ":80"

[entryPoints.https]
address = ":443"

[entryPoints.https.tls]

[acme]
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onDemand = false
onHostRule = true
acmeLogging = true

[acme.httpChallenge]
entryPoint = "http"

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = false
