version: '3'

services:
  app:
    image: linuxserver/radarr
    container_name: radarr
    ports:
      - 7878:7878
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - media:/downloads
      - media:/movies
      - config:/config
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - traefik.enable=true
      - traefik.port=7878
      - traefik.frontend.rule=Host:${traefik_url}
      - traefik.home=true
      - traefik.home.image=logos/radarr.png
      - traefik.home.category=Downloads

volumes:
  media:
    external: true
  config:
    driver: "local"
