version: '3'

volumes:
  config: {}
  media:
    external: true

networks:
  default: {}
  core_proxy:
    external: true

services:
  app:
    image: linuxserver/radarr
    container_name: radarr
    restart: always
    ports:
      - 7878:7878
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - media:/downloads
      - media:/movies
      - config:/config
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - default
      - core_proxy
    labels:
      - traefik.enable=true
      - traefik.port=7878
      - traefik.frontend.rule=Host:${url}
      - traefik.frontend.auth.basic=${auth}
      - ghosts.host=${url}
      - ghosts.proto=https
      - ghosts.auth=true
      - ghosts.logo=static/logos/radarr.png
      - ghosts.category=downloads

