version: '3'

services:
  app:
    image: linuxserver/calibre-web
    container_name: calibre-web
    ports:
      - 8083:8083
    volumes:
      - media:/books
      - config:/config
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - traefik.enable=true
      - traefik.port=8083
      - traefik.frontend.rule=Host:${traefik_url}
      - traefik.home=true
      - traefik.home.image=logos/calibre.png
      - traefik.home.category=Books

volumes:
  config:
    driver: "local"
  media:
    external: true
