version: '3'

volumes:
  config: {}
  media:
    external: true

networks:
  default: {}
  core_proxy:
    external: true

services:
  app:
    image: linuxserver/calibre-web
    container_name: calibre-web
    restart: always
    ports:
      - 8083:8083
    volumes:
      - media:/books
      - config:/config
      - ./kindlegen:/app/calibre-web/vendor/kindlegen
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - default
      - core_proxy
    labels:
      - traefik.enable=true
      - traefik.port=8083
      - traefik.frontend.rule=Host:${url}
      - traefik.docker.network=core_proxy
      - ghosts.host=${url}
      - ghosts.proto=https
      - ghosts.logo=static/logos/calibre.png
      - ghosts.category=media

