version: '3'

services:
  app:
    image: linuxserver/couchpotato
    container_name: couchpotato
    ports:
      - 5050:5050
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - media:/downloads
      - media:/movies
      - config:/config
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - traefik.enable=true
      - traefik.port=5050
      - traefik.frontend.rule=Host:${traefik_url}
      - traefik.frontend.entryPoints=${traefik_protocol:-http}
      - traefik.home=true

volumes:
  media:
    external: true
  config:
    driver: "local"
