version: '3'

services:
  proxy:
    image: nginx
    container_name: nginx
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:nginx.docker.localhost
      - traefik.frontend.entryPoints=http
      - traefik.home=true
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
