version: '3'

volumes:
  lab: {}

networks:
  default: {}
  core_proxy:
    external: true

services:
  app:
    image: lobre/vscode
    command: --allow-http --password ${password}
    container_name: vscode
    restart: always
    volumes:
      - lab:/home/dev/Lab
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      - core_proxy
    labels:
      - traefik.enable=true
      - traefik.port=8443
      - traefik.frontend.rule=Host:${url}
      - traefik.frontend.redirect.entryPoint=https
      - traefik.docker.network=core_proxy
      - ghosts.host=${url}
      - ghosts.proto=https
      - ghosts.logo=static/logos/vscode.png
      - ghosts.category=tools
