version: '3'

volumes:
  config: {}
  media:
    external: true

networks:
  default: {}
  core_proxy:
    external: true

services:
  app:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    ports:
      - 9117:9117
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - media:/downloads
      - config:/config
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - default
      - core_proxy
    labels:
      - traefik.enable=true
      - traefik.port=9117
      - traefik.frontend.rule=Host:${url}
      - ghosts.host=${url}
      - ghosts.proto=https
      - ghosts.logo=static/logos/jackett.png
      - ghosts.category=downloads

