version: '3'

services:
  app:
    image: linuxserver/jackett
    container_name: jackett
    ports:
      - 9117:9117
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - media:/downloads
      - config:/config
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - traefik.enable=true
      - traefik.port=9117
      - traefik.frontend.rule=Host:${traefik_url}
      - traefik.home=true
      - traefik.home.image=logos/jackett.png
      - traefik.home.category=Downloads

volumes:
  media:
    external: true
  config:
    driver: "local"
