version: '3'

services:
  proxy:
    image: traefik:alpine
    container_name: traefik
    restart: always
    command: --docker.domain=${traefik_domain} --acme.email=${traefik_email} --logLevel=DEBUG
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - acme:/etc/traefik/acme
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:${traefik_url}
      - traefik.frontend.auth.basic=${traefik_auth}
      - traefik.home=true
      - traefik.home.image=logos/traefik.png
      - traefik.home.category=Core

volumes:
  acme:
    driver: "local"
