version: '3'

services:
  proxy:
    image: traefik:raclette-alpine
    container_name: traefik
    command: --docker.domain=${traefik_domain} --acme.email=${traefik_email} --logLevel=DEBUG
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:${traefik_url}
      - traefik.frontend.entryPoints=${traefik_protocols:-http,https}
      - traefik.frontend.auth.basic=${traefik_auth}
      - traefik.home=true
      - traefik.home.image=https://docs.traefik.io/img/traefik.logo.png
