# defaultEntryPoints must be at the top because it should not be in any table below
defaultEntryPoints = ["http", "https"]
InsecureSkipVerify = true

[web]
# Port for the status page
address = ":8080"

# Entrypoints, http and https
[entryPoints]

# http should be redirected to https
[entryPoints.http]
address = ":80"

#[entryPoints.http.redirect]
#entryPoint = "https"

[entryPoints.https]
address = ":443"

[entryPoints.https.auth.basic]
users = ["test:$apr1$UtQgZpB9$TiczkXmm2.C2HGnt/bMKa."]

[entryPoints.https.tls]
[[entryPoints.https.tls.certificates]]
CertFile = "/certs/docker.localhost.cert"
KeyFile = "/certs/docker.localhost.key"

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = false
