version: '3'

services:
  app:
    image: nicolargo/glances
    container_name: glances
    restart: always
    pid: host
    volumes:
      - ./glances.conf:/glances/conf/glances.conf
      - media:/media
    environment:
      - GLANCES_OPT=-w --disable-plugin diskio,network,sensors
    labels:
      - traefik.enable=true
      - traefik.port=61208
      - traefik.frontend.rule=Host:${traefik_url}
      - traefik.frontend.auth.basic=${traefik_auth}
      - traefik.home=true
      - traefik.home.category=Tools

volumes:
  media:
    external: true
