version: '3'

services:
  app:
    image: mybuilds/ungit
    container_name: ungit
    volumes:
      - ..:/repo
      - ${SSH_AUTH_SOCK}:/ssh-agent
      - ${HOME}/.ssh/known_hosts:/home/developer/.ssh/known_hosts
      - ${HOME}/.gitconfig:/home/developer/.gitconfig
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    labels:
      - traefik.enable=true
      - traefik.port=8448
      - traefik.frontend.rule=Host:${traefik_url}
      - traefik.frontend.entryPoints=${traefik_protocol:-http}
      - traefik.home=true
