version: '2'

services:
  app:
    image: reinblau/ungit
    container_name: ungit
    volumes:
      - "..:/repo"
      - "${SSH_AUTH_SOCK}:/ssh-agent"
      - "${HOME}/.ssh/known_hosts:/root/.ssh/known_hosts"
    env_file: app.env
    environment:
      - VIRTUAL_PORT=8448
      - SSH_AUTH_SOCK=/ssh-agent
    network_mode: "bridge"