version: '2'

services:
  elasticsearch:
    image: "elasticsearch"
    container_name: "elasticsearch"

  logstash:
    image: "logstash"
    container_name: "logstash"
    environment:
      - "TZ=Europe/Paris"
    ports:
      - "12201:12201/udp"
    volumes:
      - "./gelf.conf:/gelf.conf"
      - "logs:/var/log/logstash"
    links:
      - "elasticsearch:db"
    command: "logstash -f /gelf.conf"

  kibana:
    image: "kibana"
    container_name: "kibana"
    links:
      - "elasticsearch:elasticsearch"
    env_file: "kibana.env"

volumes:
  logs:
    driver: "local"
