version: '2'

services:
  nginx:
    image: "jwilder/nginx-proxy"
    container_name: "proxy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "certs:/etc/nginx/certs:ro"
      - "vhost:/etc/nginx/vhost.d"
      - "challenge:/usr/share/nginx/html"
      - "./passwords:/etc/nginx/htpasswd"
      - "./proxy.conf:/etc/nginx/proxy.conf"
    env_file: "nginx.env"

  letsencrypt:
    image: "jrcs/letsencrypt-nginx-proxy-companion"
    container_name: "proxy-companion"
    volumes_from:
      - "nginx"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "certs:/etc/nginx/certs:rw"

volumes:
  certs:
    driver: "local"
  vhost:
    driver: "local"
  challenge:
    driver: "local"
