version: '3'

volumes:
  config: {}
  media:
    external: true

networks:
  default: {}
  core_proxy:
    external: true

services:
  app:
    image: linuxserver/deluge
    container_name: deluge
    restart: always
    ports:
      - 8112:8112
      - 58846:58846
    volumes:
      - media:/downloads
      - config:/config
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - default
      - core_proxy
    labels:
      - traefik.enable=true
      - traefik.port=8112
      - traefik.frontend.rule=Host:${url}
      - traefik.frontend.redirect.entryPoint=https
      - traefik.docker.network=core_proxy
      - ghosts.host=${url}
      - ghosts.proto=https
      - ghosts.logo=static/logos/deluge.png
      - ghosts.category=downloads

