version: '3'

services:
  app:
    image: linuxserver/deluge
    container_name: deluge
    restart: always
    ports:
      - 8112:8112
      - 58846:58846
    volumes:
      - media:/downloads
      - config:/config
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - traefik.enable=true
      - traefik.port=8112
      - traefik.frontend.rule=Host:${url}
      - ghosts.hosts=${url}
      - ghosts.proto=https
      - ghosts.logo=static/logos/deluge.png
      - ghosts.category=downloads

volumes:
  media:
    external: true
  config:
    driver: "local"
