version: '3'

networks:
  default: {}
  core_proxy:
    external: true

services:
  app:
    image: sspreitzer/shellinabox
    container_name: terminal
    restart: always
    environment:
      - SIAB_SUDO=true
      - SIAB_USER=${user}
      - SIAB_PASSWORD=${password}
    networks:
      - default
      - core_proxy
    labels:
      - traefik.enable=true
      - traefik.port=4200
      - traefik.protocol=https
      - traefik.frontend.rule=Host:${url}
      - ghosts.host=${url}
      - ghosts.proto=https
      - ghosts.logo=static/logos/terminal.png
      - ghosts.category=dev
