version: '3'

services:
  app:
    image: linuxserver/lazylibrarian
    container_name: lazylibrarian
    ports:
      - 5299:5299
    volumes:
      - media:/downloads
      - media:/books
      - config:/config
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - traefik.enable=true
      - traefik.port=5299
      - traefik.frontend.rule=Host:${traefik_url}
      - traefik.home=true
      - traefik.home.alias=LazyLibrarian
      - traefik.home.image=logos/lazylibrarian.png
      - traefik.home.category=Downloads

volumes:
  media:
    external: true
  config:
    driver: "local"
