version: '3'

services:
  app:
    image: gogs/gogs
    container_name: gogs
    ports:
      - "3000:3000"
      - "10022:22"
    volumes:
      - gogs:/data
    labels:
      - traefik.enable=true
      - traefik.port=3000
      - traefik.frontend.rule=Host:${traefik_url}
      - traefik.frontend.entryPoints=${traefik_protocol:-https}
      - traefik.home=true

volumes:
  gogs:
    driver: "local"
