version: '3'

services:
  app:
    image: gogs/gogs
    container_name: gogs
    ports:
      - "10022:22"
    volumes:
      - data:/data
    labels:
      - traefik.enable=true
      - traefik.port=3000
      - traefik.frontend.rule=Host:${traefik_url}
      - traefik.home=true
      - traefik.home.image=logos/gogs.png
      - traefik.home.category=Dev

volumes:
  data:
    driver: "local"
