version: '3'

services:
  app:
    image: linuxserver/plexpy
    container_name: plexpy
    restart: always
    ports:
      - 8181:8181
    volumes:
      - logs:/logs:ro
      - config:/config
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - traefik.enable=true
      - traefik.port=8181
      - traefik.frontend.rule=Host:${url}
      - ghosts.host=${url}
      - ghosts.proto=https
      - ghosts.logo=static/logos/plexpy.png
      - ghosts.category=media

volumes:
  logs:
    driver: "local"
  config:
    driver: "local"
