version: '3'

volumes:
  logs: {}
  config: {}

networks:
  default: {}
  core_proxy:
    external: true

services:
  app:
    image: linuxserver/plexpy
    container_name: plexpy
    restart: always
    ports:
      - 8181:8181
    volumes:
      - logs:/logs:ro
      - config:/config
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - default
      - core_proxy
    labels:
      - traefik.enable=true
      - traefik.port=8181
      - traefik.frontend.rule=Host:${url}
      - traefik.docker.network=core_proxy
      - ghosts.host=${url}
      - ghosts.proto=https
      - ghosts.logo=static/logos/plexpy.png
      - ghosts.category=media

