version: '3'

services:
  nginx:
    image: nginx
    container_name: home
    volumes:
      - web:/usr/share/nginx/html
      - ./style.css:/usr/share/nginx/html/style.css
      - ./favicon.ico:/usr/share/nginx/html/favicon.ico
      - ./logo.png:/usr/share/nginx/html/logo.png
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:${traefik_url}
      - traefik.frontend.entryPoints=${traefik_protocols:-http,https}
      - traefik.frontend.auth.basic=${traefik_auth}
      - traefik.home=false
      - traefik.home.navbgcolor=#89a3ff
      - traefik.home.navtextcolor=#000
      - traefik.home.title=My Apps

  gen:
    image: jwilder/docker-gen
    container_name: home-gen
    command: -watch -only-exposed /etc/docker-gen/templates/template.html /web/index.html
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./template.html:/etc/docker-gen/templates/template.html
      - web:/web

volumes:
  web:
    driver: local
