version: '3'

services:
  nginx:
    image: lobre/traefik-home
    container_name: home
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./logos:/usr/share/nginx/html/logos
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:${traefik_url}
      - traefik.home=false
      - traefik.home.navbgcolor=#89a3ff
      - traefik.home.navtextcolor=#000
      - traefik.home.title=Home
